<p style="font-size:30px;">ROC Curve</p>

It is used for threshold manipulation in classification techniques. More specifically talking about binary classification
It is used to obtain a optimal threshold of the problem reching the closest from the ideal state

In [1]:
import pandas as pd

data = pd.read_csv('https://raw.githubusercontent.com/npradaschnor/Pima-Indians-Diabetes-Dataset/master/diabetes.csv')

data.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1


In [3]:
X = data.drop('Outcome', axis=1)
y = data['Outcome']


In [4]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=2)

In [5]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add a L2 penalty term and it is the default choice;- `'l1'`: add a L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'` and `l1_ratio` set to any float between 0 and 1 for `'penalty='elasticnet'`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation `) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary ` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default solver because it works reasonably well for a wide class of problems.- For :term:`mul

In [6]:
y_scores = model.predict_proba(X_test)[:,1]

In [7]:
y_scores

array([0.0495376 , 0.17459071, 0.09362513, 0.2551022 , 0.63549763,
       0.11671255, 0.06567149, 0.42191788, 0.04865943, 0.57564545,
       0.33874537, 0.41301962, 0.69855052, 0.19964051, 0.02001651,
       0.82469077, 0.86657545, 0.03101256, 0.25510051, 0.89492636,
       0.95245335, 0.83477975, 0.11740834, 0.44670755, 0.08923396,
       0.0688207 , 0.65116518, 0.41197506, 0.17861729, 0.28689366,
       0.24548703, 0.43901236, 0.00942506, 0.24259232, 0.35169128,
       0.96164473, 0.34359585, 0.80923856, 0.29380795, 0.05083306,
       0.1818489 , 0.08672337, 0.42228328, 0.18738343, 0.03011727,
       0.0394937 , 0.24741239, 0.42782187, 0.10529443, 0.37970895,
       0.99355865, 0.10667889, 0.39101596, 0.7688143 , 0.36866148,
       0.45774882, 0.95035341, 0.41991928, 0.39156094, 0.04376209,
       0.37293033, 0.901279  , 0.88176163, 0.88842918, 0.33084351,
       0.0693201 , 0.95264199, 0.20055758, 0.26055491, 0.35462971,
       0.10359055, 0.08168641, 0.45044035, 0.09221339, 0.08648

In [ ]:
from sklearn.metrics import roc_curve

fpr, tpr, thresholds = roc_curve(y_test, y_scores)

In [15]:
fpr

array([0.        , 0.        , 0.        , 0.00917431, 0.00917431,
       0.02752294, 0.02752294, 0.0733945 , 0.0733945 , 0.08256881,
       0.08256881, 0.09174312, 0.09174312, 0.10091743, 0.10091743,
       0.11009174, 0.11009174, 0.12844037, 0.12844037, 0.14678899,
       0.14678899, 0.1559633 , 0.1559633 , 0.17431193, 0.17431193,
       0.18348624, 0.18348624, 0.22018349, 0.22018349, 0.30275229,
       0.30275229, 0.35779817, 0.35779817, 0.3853211 , 0.3853211 ,
       0.40366972, 0.40366972, 0.42201835, 0.42201835, 0.53211009,
       0.53211009, 0.5412844 , 0.5412844 , 0.57798165, 0.57798165,
       0.63302752, 0.63302752, 0.66055046, 0.66055046, 0.74311927,
       0.74311927, 0.98165138, 0.98165138, 1.        ])

In [9]:
thresholds

array([       inf, 0.99355865, 0.95264199, 0.95245335, 0.82469077,
       0.7688143 , 0.76201063, 0.68388593, 0.67532491, 0.67422076,
       0.65116518, 0.65084109, 0.63549763, 0.58629146, 0.57564545,
       0.56975889, 0.52518837, 0.47019234, 0.46128359, 0.45044035,
       0.43901236, 0.43864837, 0.42228328, 0.41991928, 0.41301962,
       0.41197506, 0.40477544, 0.37970895, 0.36866148, 0.31019998,
       0.30880321, 0.27772077, 0.27203801, 0.25845709, 0.2551022 ,
       0.24741239, 0.24548703, 0.23663601, 0.22887558, 0.1818489 ,
       0.17861729, 0.17459071, 0.17327153, 0.14637982, 0.14076711,
       0.11671255, 0.11494414, 0.11000453, 0.10667889, 0.08923396,
       0.08672337, 0.02001651, 0.01931265, 0.00160784])

In [11]:
import plotly.graph_objects as go
import numpy as np


# Generate a trace for ROC curve
trace0 = go.Scatter(
    x=fpr,
    y=tpr,
    mode='lines',
    name='ROC curve'
)

# Only label every nth point to avoid cluttering
n = 10
indices = np.arange(len(thresholds)) % n == 0  # Choose indices where index mod n is 0

trace1 = go.Scatter(
    x=fpr[indices],
    y=tpr[indices],
    mode='markers+text',
    name='Threshold points',
    text=[f"Thr={thr:.2f}" for thr in thresholds[indices]],
    textposition='top center'
)


# Diagonal line
trace2 = go.Scatter(
    x=[0, 1],
    y=[0, 1],
    mode='lines',
    name='Random (Area = 0.5)',
    line=dict(dash='dash')
)

data = [trace0, trace1, trace2]

# Define layout with square aspect ratio
layout = go.Layout(
    title='Receiver Operating Characteristic',
    xaxis=dict(title='False Positive Rate'),
    yaxis=dict(title='True Positive Rate'),
    autosize=False,
    width=800,
    height=800,
    showlegend=False
)

# Define figure and add data
fig = go.Figure(data=data, layout=layout)

# Show figure
fig.show()


In [12]:
optimal_idx = np.argmax(tpr - fpr)
optimal_threshold = thresholds[optimal_idx]
print("Optimal threshold is:", optimal_threshold)


Optimal threshold is: 0.3686614815032027


In [13]:
import plotly.graph_objects as go
import numpy as np
from sklearn.metrics import roc_auc_score

# Assuming fpr, tpr, thresholds are already calculated as before
fpr, tpr, thresholds = roc_curve(y_test, y_scores)

# Calculate the AUC (Area Under the Curve)
roc_auc = roc_auc_score(y_test, y_scores)

# Generate a trace for ROC curve
trace0 = go.Scatter(
    x=fpr,
    y=tpr,
    mode='lines',
    name=f'ROC curve (Area = {roc_auc:.2f})'
)

# Only label every nth point to avoid cluttering
n = 10
indices = np.arange(len(thresholds)) % n == 0  # Choose indices where index mod n is 0

trace1 = go.Scatter(
    x=fpr[indices],
    y=tpr[indices],
    mode='markers+text',
    name='Threshold points',
    text=[f"Thr={thr:.2f}" for thr in thresholds[indices]],
    textposition='top center'
)

# Diagonal line
trace2 = go.Scatter(
    x=[0, 1],
    y=[0, 1],
    mode='lines',
    name='Random (Area = 0.5)',
    line=dict(dash='dash')
)

data = [trace0, trace1, trace2]

# Define layout with square aspect ratio
layout = go.Layout(
    title='Receiver Operating Characteristic',
    xaxis=dict(title='False Positive Rate'),
    yaxis=dict(title='True Positive Rate'),
    autosize=False,
    width=800,
    height=800,
    showlegend=True
)

# Define figure and add data
fig = go.Figure(data=data, layout=layout)

# Show figure
fig.show()


In [14]:
import numpy as np
import plotly.graph_objects as go
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import roc_curve, roc_auc_score
from sklearn.preprocessing import StandardScaler

# Assuming that X_train, X_test, y_train, y_test are already defined

# SVM requires feature scaling for better performance
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Logistic Regression model
lr_model = LogisticRegression(max_iter=1000)
lr_model.fit(X_train, y_train)
lr_scores = lr_model.predict_proba(X_test)[:,1]

# SVM model
svm_model = SVC(probability=True)
svm_model.fit(X_train_scaled, y_train)
svm_scores = svm_model.predict_proba(X_test_scaled)[:,1]

# Generate ROC curve data for logistic regression model
lr_fpr, lr_tpr, lr_thresholds = roc_curve(y_test, lr_scores)
lr_auc = roc_auc_score(y_test, lr_scores)

# Generate ROC curve data for SVM model
svm_fpr, svm_tpr, svm_thresholds = roc_curve(y_test, svm_scores)
svm_auc = roc_auc_score(y_test, svm_scores)

# Generate a trace for the Logistic Regression ROC curve
trace0 = go.Scatter(
    x=lr_fpr,
    y=lr_tpr,
    mode='lines',
    name=f'Logistic Regression (Area = {lr_auc:.2f})'
)

# Generate a trace for the SVM ROC curve
trace1 = go.Scatter(
    x=svm_fpr,
    y=svm_tpr,
    mode='lines',
    name=f'SVM (Area = {svm_auc:.2f})'
)

# Diagonal line
trace2 = go.Scatter(
    x=[0, 1],
    y=[0, 1],
    mode='lines',
    name='Random (Area = 0.5)',
    line=dict(dash='dash')
)

data = [trace0, trace1, trace2]

# Define layout with square aspect ratio
layout = go.Layout(
    title='Receiver Operating Characteristic',
    xaxis=dict(title='False Positive Rate'),
    yaxis=dict(title='True Positive Rate'),
    autosize=False,
    width=800,
    height=800,
    showlegend=True
)

# Define figure and add data
fig = go.Figure(data=data, layout=layout)

# Show figure
fig.show()


In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import roc_curve, accuracy_score, classification_report

# -----------------------------
# 1. SAMPLE DATA (replace with your dataset)
# -----------------------------
texts = [
    "free money now",
    "hi how are you",
    "win a lottery prize",
    "let's meet tomorrow",
    "cheap loan available",
    "project meeting schedule"
]

labels = [1, 0, 1, 0, 1, 0]  # 1 = spam, 0 = not spam

# -----------------------------
# 2. TRAIN TEST SPLIT
# -----------------------------
X_train, X_test, y_train, y_test = train_test_split(
    texts, labels, test_size=0.3, random_state=42
)

# -----------------------------
# 3. TEXT VECTORIZATION
# -----------------------------
vectorizer = CountVectorizer()
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

# -----------------------------
# 4. TRAIN NAIVE BAYES MODEL
# -----------------------------
model = MultinomialNB()
model.fit(X_train_vec, y_train)

# -----------------------------
# 5. GET PROBABILITIES (IMPORTANT)
# -----------------------------
y_prob = model.predict_proba(X_test_vec)[:, 1]

# -----------------------------
# 6. FIND / USE OPTIMAL THRESHOLD
# -----------------------------
threshold = 0.36   # your chosen value

y_pred = (y_prob >= threshold).astype(int)

# -----------------------------
# 7. EVALUATION
# -----------------------------
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

# -----------------------------
# 8. PREDICT NEW EMAIL
# -----------------------------
def predict_email(text):
    vec = vectorizer.transform([text])
    prob = model.predict_proba(vec)[0, 1]

    prediction = "SPAM" if prob >= threshold else "NOT SPAM"

    print("\nEmail:", text)
    print("Spam Probability:", prob)
    print("Prediction:", prediction)

# -----------------------------
# 9. TEST
# -----------------------------
predict_email("you won free lottery prize")
predict_email("can we meet tomorrow?")